version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_rabbitmq_data: {}

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"   # I like working on 80 since you don't need to specify and looking neat on URL
    volumes:
      - ./compose/production/nginx/:/etc/nginx/conf.d
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: conference_scrapper_production_python
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=scrapper
      - POSTGRES_PASSWORD=scrapper
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq//
    command: /start
    expose:
      - 8000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: conference_scrapper_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=scrapper
      - POSTGRES_PASSWORD=scrapper
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
