# Generated by Django 2.1.7 on 2019-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20190313_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='source',
            field=models.CharField(default='acm', max_length=32),
            preserve_default=False,
        ),
    ]
