# Generated by Django 2.1.7 on 2019-03-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_conference_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
