# Generated by Django 2.1.7 on 2019-03-18 18:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_conference_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
    ]
