# Generated by Django 2.1.7 on 2019-03-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_conference_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_1', models.CharField(db_index=True, max_length=32)),
                ('conf_2', models.CharField(db_index=True, max_length=32)),
                ('matches_len', models.PositiveSmallIntegerField()),
                ('matches', models.CharField(max_length=512)),
                ('source', models.CharField(max_length=32)),
            ],
        ),
    ]
