# Generated by Django 2.1.7 on 2019-03-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_conferenceedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceGraphInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.PositiveIntegerField()),
                ('y_coord', models.PositiveIntegerField()),
                ('degree', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ConferenceEdge',
            new_name='ConferenceGraphEdge',
        ),
        migrations.AddField(
            model_name='conference',
            name='graph_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.ConferenceGraphInfo'),
        ),
    ]
