# Generated by Django 2.1.7 on 2019-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20190324_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='graph_info',
        ),
        migrations.AddField(
            model_name='conference',
            name='degree',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='x_coord',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='y_coord',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConferenceGraphInfo',
        ),
    ]
