# Generated by Django 2.1.7 on 2019-03-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20190324_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='conferencegraphedge',
            name='conf_1',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='conferencegraphedge',
            name='conf_2',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
