# Generated by Django 2.1.7 on 2019-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_auto_20190324_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='x_coord',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='y_coord',
            field=models.FloatField(),
        ),
    ]
